### ISSUE TITLE
Bug during loading plugin on new widget

### ISSUE THREAD

**Issue by cyber5tar86** [alexandrainst/alexandra-trackmap-panel#102]
hi!
i'm trying to use the plugin on a new widget, but as soon as i select it from right pane (from "change visualization"), a crash occur; hereinafter the stack strace:

TypeError: Cannot read properties of undefined (reading 'emit')

    at fn (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:102:1844)
    at g (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1042467)
    at div
    at div
    at div
    at t (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:711587)
    at p (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:424:3279)
    at div
    at div
    at Kn (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:135:4496)
    at div
    at div
    at Ii (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:258:27)
    at div
    at n (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:37:6451)
    at div
    at n (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:37:8400)
    at _t (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:37:13987)
    at div
    at div
    at div
    at b (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:5866:1143)
    at ya (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:381:1376)
    at g (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1042467)
    at WithTheme(Connect(ya))
    at Rr (http://localhost:3000/public/build/DashboardPage.126ca076ff8cc9a03c55.js:490:7179)
    at DashboardPage
    at g (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1042467)
    at Suspense
    at c (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:1207:301)
    at ts (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:5576:348)
    at t (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1060860)
    at t (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1062881)
    at main
    at Rt (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:5537:6824)
    at t (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1057478)
    at div
    at o (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:2005:4594)
    at t.KBarProvider (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:271052)
    at l (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:6297:20329)
    at c (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:1207:301)
    at u (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:1207:855)
    at l (http://localhost:3000/public/build/805.dbf9890c776d9ed0196c.js:2:1040512)
    at As (http://localhost:3000/public/build/7180.891e478ea88d9b79781e.js:5589:167)

**Comment by oxo42** [comment]
I see you posted this 8 months ago.  Any update?
