### ISSUE TITLE
Newest versions available on Grafana Cloud

### ISSUE THREAD

**Issue by stijnder** [alexandrainst/alexandra-trackmap-panel#65]
Hi, 

I'm using Grafana Cloud (8.0.4), and I would very much like to use this plugin. The latest version available to install from https://grafana.com/grafana/plugins/alexandra-trackmap-panel/?tab=installation is 1.2.6, which I think is not compatible with this Grafana version. I don't think I have another option to manually install the latest version (2.2.1) of this plugin in Grafana Cloud.
I'm now getting a stacktrace when trying to add a panel with the Trackmap vizualization:
```
TypeError: Cannot read property 'emit' of undefined

    at Xt (https://grafana-assets.grafana.net/grafana-pro/8.0.4/public/build/DashboardPage.15a18d43ff262349d5e8.js:223:4307)
    at k (https://grafana-assets.grafana.net/grafana-pro/8.0.4/public/build/vendors~app.15a18d43ff262349d5e8.js:2:70367)
    at div
    at div
    at div
    at t (https://grafana-assets.grafana.net/grafana-pro/8.0.4/public/build/vendors~app.15a18d43ff262349d5e8.js:2:706836)
```

Regards, Stijn

**Comment by ZhongyuWang** [comment]
Hi,

I have not tried to install the plugin on the Grafana Cloud. I would like to know if it is possible to install the plugin manualy from the release. I guess why the plugin is not available is that it is not signed at the moment.

To install the plugin with Grafana 8 locally or with docker, the environment variable GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS needs to be set. Ex. GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexandra-trackmap-panel

Best regards,
Zhongyu

**Comment by anirudh-ramesh** [comment]
Identical to #72.
